blank_issues_enabled: true
contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/dlshriver/intercepts/discussions
    about: Some common problems and questions are discussed here.
